version: '3'

services:
  redis:
    image: "redis:alpine"

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: sh -c "python manage.py migrate && gunicorn test_file_celery.wsgi:application --bind 0.0.0.0:8000"


  celery:
    build:
      context: .
    volumes:
      - .:/app
    command: celery -A test_file_celery worker --loglevel=info
    depends_on:
      - redis
      - web
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./test.conf:/etc/nginx/nginx.conf
    depends_on:
      - web


