# Generated by Django 4.2.5 on 2023-09-25 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='file')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='uploaded at')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
            ],
        ),
    ]
